Repository Codeit-FE-5-part4-7/nomad, pull requests merged in 2024-08, with the labels that each got.

#81 [Feat] 이미지 확대 모달 추가
  public/icons/Icon_slider_left_arrow.svg
  public/icons/Icon_slider_right_arrow.svg
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/FloatingCard/TabletSize/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/Map/index.tsx
  src/components/Slider/index.tsx
  src/pages/activity-detail/index.tsx
  src/pages/activity-detail/layout.tsx
  src/styles/calendar.module.css
  src/styles/slider.module.css
  tailwind.config.js
Labels: Priority: Low 🐢, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#83 [Feat] 이미지 원본 다운로드 추가
  public/icons/Icon_download.svg
  public/icons/Icon_slider_left_arrow.svg
  src/components/Button/index.tsx
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/FloatingCard/MobileSize/index.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Map/index.tsx
  src/components/ReservationContent/index.tsx
  src/constant/importImages.ts
  src/styles/calendar.module.css
  src/styles/globals.css
  src/styles/slider.module.css
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#85 [Feat] 자동 배포를 위한 build파일 생성
  .github/workflows/deploy.yml
  build.sh
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#89 [Fix]:Reservation Z-index변경, 다크모드 아이콘 추가, 등록 체험 없을 시 처리
  public/icons/Icon_X_D_bold.svg
  src/components/Modal/ModalContents/reservation-info/ReservationInfo.tsx
  src/pages/my/reservation-dashboard/ActivityDropDown.tsx
  src/pages/my/reservation-dashboard/calendar.tsx
  src/pages/my/reservation-dashboard/index.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Improve UX :arrow_up:

#93 [Feat] 이미지 확대 모달 스와이프 추가
  package-lock.json
  package.json
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/ReviewList/index.tsx
  src/components/Slider/index.tsx
  src/pages/_app.tsx
  src/pages/activity-detail/index.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
  src/styles/swiper.module.css
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#98 [Release] 3차 배포
  package-lock.json
  package.json
  src/apis/axios.ts
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/DropdownMenu/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/ReviewList/index.tsx
  src/components/ScheduleListItem/index.tsx
  src/components/Slider/index.tsx
  src/components/landing-page/CardResource.tsx
  src/pages/_app.tsx
  src/pages/activity-detail/index.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/postactivity/index.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
  src/styles/swiper.module.css
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Refactor :recycle:

#101 [Fix] 페이지 CSS 수정 / 푸터 고정
  src/components/CardList/AcitivitiesCardList/index.tsx
  src/components/CardList/NoCards/index.tsx
  src/components/DropdownMenu/index.tsx
  src/components/FilterButton/FilterDropButton/index.tsx
  src/components/Layout/index.tsx
  src/components/Modal/ModalContents/review/RatingInput.tsx
  src/components/Modal/ModalContents/review/Review.tsx
  src/components/Modal/ModalContents/review/ReviewForm.tsx
  src/components/Review/ReviewForm/index.tsx
  src/components/Review/index.tsx
  src/pages/my/reservation-dashboard/index.tsx
  src/pages/my/reservation-history/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#102 [fix]알림창 닫기 기능 추가, 다크모드 적용
  public/icons/Icon_Ellipse_D.svg
  src/components/Layout/Header/index.tsx
  src/components/Modal/ModalContents/notifications/index.tsx
  src/constant/importImages.ts
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#103 [Fix] 페이지네이션 오류 수정 & css와 다크모드 수정 & 건물명 없는 경우 처리
  public/icons/Icon_close_dark_mode.svg
  src/apis/get/getActivityDetail.ts
  src/components/Button/index.tsx
  src/components/Calendar/index.tsx
  src/components/CustomPopup/index.tsx
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/FloatingCard/MobileSize/index.tsx
  src/components/FloatingCard/TabletSize/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/Map/index.tsx
  src/components/Pagination/PageItem/index.tsx
  src/components/Pagination/ReviewPagination/index.tsx
  src/components/Pagination/index.tsx
  src/components/ReservationContent/index.tsx
  src/components/ReviewList/ReviewItem/index.tsx
  src/components/ReviewList/index.tsx
  src/components/landing-page/CardResource.tsx
  src/constant/importImages.ts
  src/hooks/useAuthRedirect.ts
  src/hooks/useReservation.ts
  src/pages/activity-detail/[id].tsx
  src/pages/activity-detail/index.tsx
  src/pages/activity-detail/layout.tsx
  src/styles/swiper.module.css
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Improve UX :arrow_up:

#104 4차 배포
  public/icons/Icon_Ellipse_D.svg
  public/icons/Icon_close_dark_mode.svg
  src/apis/get/getActivityDetail.ts
  src/components/Button/index.tsx
  src/components/Calendar/index.tsx
  src/components/CardList/AcitivitiesCardList/index.tsx
  src/components/CardList/NoCards/index.tsx
  src/components/CustomPopup/index.tsx
  src/components/DialogsModal/ModalContent/ImageModal/index.tsx
  src/components/DropdownMenu/index.tsx
  src/components/FilterButton/FilterDropButton/index.tsx
  src/components/FloatingCard/MobileSize/index.tsx
  src/components/FloatingCard/TabletSize/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/index.tsx
  src/components/Map/index.tsx
  src/components/Modal/ModalContents/notifications/index.tsx
  src/components/Modal/ModalContents/review/RatingInput.tsx
  src/components/Modal/ModalContents/review/Review.tsx
  src/components/Modal/ModalContents/review/ReviewForm.tsx
  src/components/Pagination/PageItem/index.tsx
  src/components/Pagination/ReviewPagination/index.tsx
  src/components/Pagination/index.tsx
  src/components/ReservationContent/index.tsx
  src/components/Review/ReviewForm/index.tsx
  src/components/Review/index.tsx
  src/components/ReviewList/ReviewItem/index.tsx
  src/components/ReviewList/index.tsx
  src/components/landing-page/CardResource.tsx
  src/constant/importImages.ts
  src/hooks/useAuthRedirect.ts
  src/hooks/useReservation.ts
  src/pages/activity-detail/[id].tsx
  src/pages/activity-detail/index.tsx
  src/pages/activity-detail/layout.tsx
  src/pages/my/reservation-dashboard/index.tsx
  src/pages/my/reservation-history/index.tsx
  src/styles/swiper.module.css
Labels: Priority: Medium :bookmark:

#105 [Fix] 다크모드 전환 속도 조정
  src/components/FloatingCard/TabletSize/index.tsx
  src/pages/activity-detail/index.tsx
  src/styles/globals.css
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#117 [Fix] 페이지네이션 ui & 리로드 현상 수정
  src/components/Pagination/index.tsx
  src/components/ReviewList/ReviewItem/index.tsx
  src/pages/activity-detail/index.tsx
  src/styles/swiper.module.css
Labels: Priority: Low 🐢, Type: Bug :bug:

#118 [Fix] CSS 수정
  src/components/SideNavigation/MobileSize/index.tsx
  src/components/landing-page/ActivitiesList.tsx
  src/components/landing-page/CardResource.tsx
  src/components/landing-page/Filter.tsx
  src/components/landing-page/Search.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#122 [Fix] 메인페이지 CSS
  src/components/landing-page/Banner.tsx
  src/components/landing-page/CardResource.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:
