Repository Codeit-FE-5-part4-7/nomad, pull requests merged in 2024-07, with the labels that each got.

#1 PR Test1
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/pages/index.tsx
Labels: Priority: Low 🐢

#3 [Feat] : global.css html에 font-size 62.5% 추가
  src/pages/_document.tsx
  src/styles/globals.css
Labels: Priority: Low 🐢

#2 feat: 폴더구조 정리
  public/images/gom.png
  public/svgs/logo_small.svg
  src/apis/example.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/example.ts
  src/constant/constant.ts
  src/context/example.ts
  src/hooks/example.ts
  src/hooks/userQueryHooks.ts
  src/pages/api/hello.ts
  src/schema/user.ts
  src/types/query.ts
  src/utils/ex.ts
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#4 초기셋팅 병합
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  public/images/gom.png
  public/svgs/logo_small.svg
  src/apis/example.ts
  src/apis/index.ts
  src/apis/queries.ts
  src/apis/user.ts
  src/components/example.ts
  src/constant/constant.ts
  src/context/example.ts
  src/hooks/example.ts
  src/hooks/userQueryHooks.ts
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/schema/user.ts
  src/styles/globals.css
  src/types/query.ts
  src/utils/ex.ts
Labels: Priority: High 🔥, Type: Epic :rocket:

#6 [Feat] Layout 설정
  src/components/Layout/Footer/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/index.tsx
  src/components/example.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#7 [Feat] Button 컴포넌트
  .eslintrc.js
  src/components/Button/CustomButton/index.tsx
  src/components/Button/GrayButton/index.tsx
  src/pages/preview/index.tsx
  src/styles/globals.css
Labels: Priority: High 🔥, Type: Merge :truck:

#5 [feat]카드 컴포넌트 뼈대 제작 및 글로벌 css 일부 삭제
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/components/Card/index.tsx
  src/components/Card/myActibityCardInfo/index.tsx
  src/pages/index.tsx
  src/pages/myactivities/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#8 [Feat] 내 체험 관리 카드 정보 UI 완성
  public/images/test123.png
  public/svgs/icon_meatball.svg
  public/svgs/star.svg
  src/components/Card/index.tsx
  src/components/Card/myActibityCardInfo/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#13 [Feat] Pagination 컴포넌트
  public/svgs/page-left.svg
  public/svgs/page-right.svg
  src/components/Pagination/PageItem/index.tsx
  src/components/Pagination/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: Medium :bookmark:, Type: Merge :truck:

#15 [Feat] Dialogs Modal 추가
  src/components/Button/CustomButton/index.tsx
  src/components/DialogsModal/ModalContent/AlertModal/index.tsx
  src/components/DialogsModal/ModalContent/ConfirmModal/index.tsx
  src/components/DialogsModal/index.tsx
  src/context/example.ts
  src/context/modalContext.tsx
  src/hooks/useModal.ts
  src/hooks/useModalScrollBlock.ts
  src/pages/_app.tsx
  src/pages/preview/index.tsx
  src/types/DialogsModal.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#16 [feat] 카드 리스트 컴포넌트 UI 완성
  public/svgs/no_activity.svg
  src/components/Card/myActibityCardInfo/index.tsx
  src/components/CardList/AcitivitiesCardList/index.tsx
  src/components/CardList/NoCards/index.tsx
  src/pages/myactivities/index.tsx
  src/pages/myactivities/postactivity/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#14 [Fix] Button 컴포넌트에 link 속성 추가
  src/components/Button/GrayButton/index.tsx
  src/components/Button/index.tsx
  src/components/Calender/index.tsx
  src/components/DialogsModal/ModalContent/AlertModal/index.tsx
  src/components/DialogsModal/ModalContent/ConfirmModal/index.tsx
  src/components/Pagination/index.tsx
  src/pages/activity-detail/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#18 [Feat] 사이드 네비게이션 컴포넌트 추가
  next.config.mjs
  public/icons/Icon_account_check_noSelect.svg
  public/icons/Icon_calendar_check_noSelect.svg
  public/icons/Icon_setting_noSelect.svg
  public/icons/Icon_text-box_check_noSelect.svg
  src/components/DialogsModal/ModalContent/AlertModal/index.tsx
  src/components/SideNavigation/index.tsx
  src/constant/importImages.ts
  src/constant/index.js
  src/constant/sideNavOptions.ts
  src/pages/preview/index.tsx
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#17 [fix] .nvmrc 버전 수정
  .nvmrc
Labels: Priority: Low 🐢

#20 [Feat] 내 체험 등록 페이지 UI 완성
  .eslintrc.js
  public/icons/Icon_X_white.svg
  public/images/ImageInput.png
  public/svgs/icon_meatball.svg
  src/apis/get/getMyActivities.ts
  src/components/Card/ImageCard/index.tsx
  src/components/Card/index.tsx
  src/components/Card/myActibityCardInfo/index.tsx
  src/components/CardList/AcitivitiesCardList/index.tsx
  src/components/Dropdown/index.tsx
  src/components/Input/ImageInput/index.tsx
  src/components/Layout/index.tsx
  src/components/MyLayout/index.tsx
  src/components/ScheduleListItem/index.tsx
  src/pages/myactivities/editactivity/index.tsx
  src/pages/myactivities/index.tsx
  src/pages/myactivities/postactivity/index.tsx
  src/pages/preview/index.tsx
  src/utils/types/myActivities.ts
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#21 [feat] 내 체험 관리 카드 및 미트볼 버튼 api 연동 및 무한스크롤 기능 추가
  package-lock.json
  package.json
  src/apis/delete/deleteActivity.ts
  src/apis/get/getMyActivities.ts
  src/components/Card/myActibityCardInfo/index.tsx
  src/components/CardList/AcitivitiesCardList/index.tsx
  src/pages/myactivities/editactivity/[id].tsx
  src/pages/myactivities/editactivity/index.tsx
  src/pages/myactivities/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#26 Feat: 로그인, 회원가입 페이지 만듬
  package-lock.json
  package.json
  src/components/Input/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/auth/Confirm.tsx
  src/components/auth/FormHeader.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/SubmitButton.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/utils/auth/api.ts
  src/utils/auth/types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#29 tailwind config에 폰트, 색상, 미디어 쿼리 추가
  src/components/Pagination/PageItem/index.tsx
  src/pages/preview/index.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#30 [Feature] footer 수정, 예약 현황 페이지 캘린더 1차 제작
  package-lock.json
  package.json
  public/svgs/akar-icons_facebook-fill.svg
  public/svgs/akar-icons_twitter-fill.svg
  public/svgs/akar-icons_youtube-fill.svg
  public/svgs/ant-design_instagram-filled.svg
  src/components/Layout/Footer/index.tsx
  src/pages/reservationDashboard/calendar.tsx
  src/pages/reservationDashboard/index.tsx
  tailwind.config.js
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#31 fix: 입력창 수정
  package-lock.json
  package.json
  src/components/Input/index.tsx
  src/components/auth/Confirm.tsx
  src/components/landing-page/ActivitiesList.tsx
  src/components/landing-page/Banner.tsx
  src/components/landing-page/CardResource.tsx
  src/components/landing-page/Category.tsx
  src/components/landing-page/CategoryFilter.tsx
  src/components/landing-page/CustomButton.tsx
  src/components/landing-page/Filter.tsx
  src/components/landing-page/PopularActivitiesList.tsx
  src/components/landing-page/PostActivityButton.tsx
  src/components/landing-page/Question.tsx
  src/components/landing-page/SearchActivitiesHeader.tsx
  src/components/landing-page/Skeleton.tsx
  src/hooks/useResponsiveSize.ts
  src/utils/landing-page/throttle.ts
  src/utils/landing-page/types.ts
  src/utils/landing-page/useCategoryFilterStore.ts
Labels: Priority: High 🔥

#28 [Feat] 예약내역 페이지 퍼블리싱 / 필터 카테고리 컴포넌트 추가
  src/components/Card/myReservationCardInfo/index.tsx
  src/components/FilterButton/CategoryButton/index.tsx
  src/components/FilterButton/FilterDropButton/index.tsx
  src/components/SideNavigation/index.tsx
  src/constant/filterCategoryOptions.ts
  src/constant/sideNavOptions.ts
  src/pages/my/reservation-history/index.tsx
  src/pages/preview/index.tsx
  src/types/ReservationInfo.ts
  src/utils/setReservationStatueInfo.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#27 feat: 주소 찾기 이외의 내 체험 생성 페이지 데이터 입력 완성
  src/apis/get/getMyActivities.ts
  src/components/Card/ImageCard/index.tsx
  src/components/Input/ImageInput/index.tsx
  src/components/ScheduleListItem/index.tsx
  src/pages/myactivities/editactivity/[id].tsx
  src/pages/myactivities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#32 fix: 입력창 수정
  package-lock.json
  package.json
  src/components/Input/index.tsx
  src/components/auth/Confirm.tsx
  src/components/landing-page/ActivitiesList.tsx
  src/components/landing-page/Banner.tsx
  src/components/landing-page/CardResource.tsx
  src/components/landing-page/Category.tsx
  src/components/landing-page/CategoryFilter.tsx
  src/components/landing-page/CustomButton.tsx
  src/components/landing-page/Filter.tsx
  src/components/landing-page/PopularActivitiesList.tsx
  src/components/landing-page/PostActivityButton.tsx
  src/components/landing-page/Question.tsx
  src/components/landing-page/SearchActivitiesHeader.tsx
  src/components/landing-page/Skeleton.tsx
  src/hooks/useResponsiveSize.ts
  src/utils/landing-page/throttle.ts
  src/utils/landing-page/types.ts
  src/utils/landing-page/useCategoryFilterStore.ts
Labels: Priority: High 🔥

#36 Fix: Input,Dropdown 업데이트
  src/components/Dropdown/index.tsx
  src/components/Input/index.tsx
  src/components/landing-page/ActivitiesList.tsx
  src/pages/preview/index.tsx
  src/utils/auth/api.ts
Labels: Priority: Medium :bookmark:

#38 [feat] alert창 모달로 수정
  src/apis/patch/patchActivity.ts
  src/apis/post/postActivity.ts
  src/components/Card/myActibityCardInfo/index.tsx
  src/components/MyLayout/index.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/index.tsx
  src/pages/my/activities/postactivity/index.tsx
  src/pages/myactivities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#40 Fix: Dropdown 수정
  src/components/Dropdown/index.tsx
  src/pages/preview/index.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#42 [Feat] 내 정보 페이지 추가 / 프로필 이미지 변경 추가
  src/apis/patch/patchMyProfile.ts
  src/apis/post/postProfileImgUrl.ts
  src/components/SideNavigation/index.tsx
  src/constant/sideNavOptions.ts
  src/pages/my/profile/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#44 [feat] 예약 현황 페이지 api연동, 전용 드롭박스 제작
  package-lock.json
  src/apis/get/getReservationDashBoard.ts
  src/components/BookedBox/index.tsx
  src/pages/reservationDashboard/ActivityDropDown.tsx
  src/pages/reservationDashboard/calendar.tsx
  src/pages/reservationDashboard/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#46 Feat: 메인 페이지 작성
  src/components/landing-page/ActivitiesList.tsx
  src/components/landing-page/Banner.tsx
  src/components/landing-page/Category.tsx
  src/components/landing-page/CategoryFilter.tsx
  src/components/landing-page/Filter.tsx
  src/components/landing-page/MainLayout.tsx
  src/components/landing-page/MainPage.tsx
  src/components/landing-page/Pagination.tsx
  src/components/landing-page/Search.tsx
  src/components/landing-page/Skeleton.tsx
  src/pages/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#48 [feature]예약현황 상태 캘린더에 쌓기, 갯수 표시
  package-lock.json
  src/components/BookedBox/index.tsx
  src/pages/reservationDashboard/calendar.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#51 Fix: 메인 페이지 UI 조정
  src/components/Modal/ModalContents/index.tsx
  src/components/landing-page/ActivitiesList.tsx
  src/components/landing-page/Banner.tsx
  src/components/landing-page/CardResource.tsx
  src/components/landing-page/CategoryFilter.tsx
  src/components/landing-page/CustomButton.tsx
  src/components/landing-page/MainLayout.tsx
  src/components/landing-page/MainPage.tsx
  src/components/landing-page/PopularActivitiesList.tsx
  src/components/landing-page/PostActivityButton.tsx
  src/components/landing-page/Search.tsx
  src/pages/preview/index.tsx
Labels: Priority: Low 🐢

#49 [Feat] 체험 상세 페이지 반응형 & 기능 & api 연결
  .eslintrc.js
  package-lock.json
  package.json
  public/images/test_kitty.png
  public/images/test_kitty2.png
  public/images/test_kitty3.png
  src/apis/get/getActivityDetail.ts
  src/components/CustomPopup/index.tsx
  src/components/DialogsModal/ModalContent/AlertModal/index.tsx
  src/components/DialogsModal/ModalContent/ConfirmModal/index.tsx
  src/components/DialogsModal/index.tsx
  src/components/FloatingBox/index.tsx
  src/components/FloatingCard/MobileSize/index.tsx
  src/components/FloatingCard/TabletSize/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/Map/index.tsx
  src/components/Pagination/index.tsx
  src/components/ReservationContent/index.tsx
  src/components/ReviewList/index.tsx
  src/components/landing-page/CardResource.tsx
  src/context/userContext.tsx
  src/hooks/usePopup.ts
  src/hooks/useReservation.ts
  src/pages/activity-detail/[id].tsx
  src/pages/activity-detail/index.tsx
  src/pages/preview/index.tsx
  src/styles/globals.css
  src/styles/slider.module.css
  src/types/ActivityDetail.ts
  src/utils/types/reviews.ts
  src/utils/types/schedule.ts
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#52 feat : TimeInput 완성 / fix: 무한 스크롤 2번 로딩 수정
  src/components/Input/TimeInput/index.module.css
  src/components/Input/TimeInput/index.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/index.tsx
  src/pages/my/activities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#54 [Feat] 스케줄 등록 로직 및 UI 조정
  src/components/Input/TimeInput/index.tsx
  src/components/ScheduleListItem/index.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#55 [Feat] 후기작성 퍼블리싱 / 예약내역 api / 리뷰등록 api
  src/apis/get/getMyReservationList.ts
  src/apis/patch/patchCancelMyReservation.ts
  src/components/Card/myReservationCardInfo/index.tsx
  src/components/FilterButton/FilterDropButton/index.tsx
  src/components/Review/RatingInput/index.tsx
  src/components/Review/ReviewForm/index.tsx
  src/components/Review/index.tsx
  src/components/SideNavigation/index.tsx
  src/constant/filterCategoryOptions.ts
  src/pages/my/reservation-history/index.tsx
  src/pages/preview/index.tsx
  src/styles/globals.css
  src/types/ReservationInfo.ts
  src/types/StatusFilter.ts
  src/utils/setReservationStatueInfo.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#53 [Feat] 반응형 이미지 슬라이더 추가
  package-lock.json
  package.json
  src/components/ImageContainer/index.tsx
  src/components/Slider/index.tsx
  src/styles/globals.css
  src/styles/slider.module.css
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#56 refact: 내 체험 등록/수정 접근성 향상 및 스타일 적용
  src/components/Dropdown/index.tsx
  src/components/Input/TimeInput/index.tsx
  src/components/ScheduleListItem/index.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/index.tsx
  src/pages/my/activities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#57 [Feat] 예약 현황 페이지 개발 완료
  src/components/Modal/ModalContents/reservation-info/ReservationCard.tsx
  src/components/Modal/ModalContents/reservation-info/ReservationInfo.tsx
  src/pages/preview/index.tsx
  src/pages/reservation-dashboard/ActivityDropDown.tsx
  src/pages/reservation-dashboard/calendar.tsx
  src/pages/reservation-dashboard/index.tsx
  src/pages/reservationDashboard/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#58 [feat] 내 체험 수정/등록의 제목, 가격, 설명에 글자 수 제한 추가
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#59 [Fix] 예약내역 전체 필터 추가 / 사이드 네비게이션 모바일 반응형
  public/icons/Icon_left_arrow-white.svg
  public/icons/Icon_right_arrow-white.svg
  src/apis/get/getMyReservationList.ts
  src/components/Card/myReservationCardInfo/index.tsx
  src/components/DialogsModal/ModalContent/ConfirmModal/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Modal/ModalContents/reservation-info/ReservationInfo.tsx
  src/components/SideNavigation/MobileSize/index.tsx
  src/components/SideNavigation/NavigationItem/index.tsx
  src/components/SideNavigation/ProfileImage/index.tsx
  src/components/SideNavigation/index.tsx
  src/constant/filterCategoryOptions.ts
  src/constant/importImages.ts
  src/constant/sideNavOptions.ts
  src/pages/my/profile/index.tsx
  src/pages/my/reservation-dashboard/ActivityDropDown.tsx
  src/pages/my/reservation-dashboard/calendar.tsx
  src/pages/my/reservation-dashboard/index.tsx
  src/pages/my/reservation-history/index.tsx
  src/types/StatusFilter.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#62 [Fix] z-index값 수정
  src/pages/my/reservation-dashboard/calendar.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#61 Fix: DropdownMenu 사이즈 조정
  src/components/DropdownMenu/index.tsx
Labels: Priority: Medium :bookmark:

#63 [feat] 404 페이지 추가 및 다크 모드 일부 적용
  src/components/Button/MeatBall/index.tsx
  src/components/Card/index.tsx
  src/components/Card/myActibityCardInfo/index.tsx
  src/pages/404.tsx
  src/pages/my/activities/editactivity/[id].tsx
  src/pages/my/activities/index.tsx
  src/pages/my/activities/postactivity/index.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#64 [Feat] 체험 상세 페이지 기능 추가 & 다크 모드 토글 버튼 추가
  src/components/Calendar/index.tsx
  src/components/CustomPopup/index.tsx
  src/components/DarkModeButton/index.tsx
  src/components/ExpandableText/index.tsx
  src/components/FloatingCard/MobileSize/index.tsx
  src/components/FloatingCard/TabletSize/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Map/appKey.ts
  src/components/Map/index.tsx
  src/components/ReservationContent/index.tsx
  src/components/Slider/index.tsx
  src/constant/constant.ts
  src/context/themeContext.tsx
  src/context/userContext.tsx
  src/hooks/useFormatPrice.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/activity-detail/index.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
  tailwind.config.js
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#65 [Fix] 사이드 네비게이션 레이아웃 분리 / 페이지 반응형
  src/components/Card/myReservationCardInfo/index.tsx
  src/components/FilterButton/FilterDropButton/index.tsx
  src/components/MyLayout/index.tsx
  src/pages/my/profile/index.tsx
  src/pages/my/reservation-history/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#76 [Feat] 체험 상세 페이지 다크 모드 추가
  public/icons/Icon_darkmode_bell.svg
  public/icons/Icon_mapmarker_darkmode.svg
  public/images/Image_darkmode_logo.svg
  public/images/logo_big_dark_mode.png
  src/components/Button/index.tsx
  src/components/DarkModeButton/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/index.tsx
  src/components/Pagination/PageItem/index.tsx
  src/components/Pagination/index.tsx
  src/components/ReservationContent/index.tsx
  src/components/ReviewList/index.tsx
  src/constant/importImages.ts
  src/pages/activity-detail/index.tsx
  src/pages/preview/index.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#77 [Feature] 알람기능 제작
  src/components/Layout/Header/index.tsx
  src/components/Modal/ModalContents/notifications/index.tsx
  src/pages/my/reservation-dashboard/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#80 [Fix] 다크모드 버튼 변경
  public/icons/Icon_notification.svg
  src/components/DarkModeButton/index.tsx
  src/components/ExpandableText/index.tsx
  src/components/FloatingCard/index.tsx
  src/components/ImageContainer/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Map/index.tsx
  src/components/ReviewList/index.tsx
  src/pages/activity-detail/index.tsx
  src/pages/activity-detail/layout.tsx
  src/styles/calendar.module.css
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:
